### PR TITLE
A proper jailbreak needs full debugging capabilities and unrestricted usage of environment variables

### PR DESCRIPTION
**Pull request by jakeajames**
please

### CODE REVIEW

**Comment by sbingner** [comment]
Merged in https://github.com/sbingner/unrestrict/commit/61526a09a06ce4378c7a3c8213a296e141405084

**Comment by sbingner** [comment]
So I tried with and without this - and debugserver works either way... also DYLD_INSERT_LIBRARIES works fine without it.... convince me this is needed?

**Comment by jakeajames** [comment]
@sbingner did you test this with binaries that have get-task-allow? The point is enabling the functionality for system binaries which you can't resign. All DYLD_ variables are ignored when get-task-allow is missing, and debugserver works because it has task_for_pid-allow, with get-task-allow it would not be needed. Now I agree second reason is not much of an issue as you can resign, but DYLD_ variables are very 

Before and after

**Comment by jakeajames** [comment]
@sbingner i see you removed the code, did I not convince you?

Edit: I spoke with pwn, and it seems like you think I'm confused with the functionality. I know get-task-allow is used so every root process can get every task port, and that's exactly the point. Again, if you have tfp-allow that is not needed as you can get task port anyway but the additional feature it offers you are DYLD variables, which *require* get-task-allow. I showed you a screenshot, before and after adding get-task-allow, and since we can't resign system binaries, adding it in unrestrict would be useful. Add the fact that every single jailbreak so far allows this functionality, even Electra to some degree.

**Pull request merged**
