### PR TITLE
yay sandbox patches

### PR DESCRIPTION
**Pull request by jakeajames**

### CODE REVIEW

**Comment by pwn20wndstuff** [comment]
Thank you! I will merge and rebase your changes to not break iOS 10/11 support.

**Comment by jakeajames** [comment]
damn forgot this breaks iOS 11 support, gotta change that yourself

**Comment by pwn20wndstuff** [comment]
I already noticed and fixed this in my implementation - Thank you anyway.

**Comment by pwn20wndstuff** [comment]
I have manually merged these changes to preserve iOS 10 and 11 support. Closing the pull request.

**Pull request closed without merging**
